<template>
  <div class="bg-gray-600/50 drop-shadow-md backdrop-blur-sm w-fit max-w-5xl h-fit p-4 lg:p-8 2xl:p-10 mx-4 rounded-lg flex flex-col items-start justify-start text-white">
    <h1 class="text-white text-xl lg:text-2xl 2xl:text-3xl font-semibold self-center">
      About Kudosu
    </h1>

    <p class="pt-10 max-w-3xl xl:text-lg">
      Kudosu is a simple open-source Laravel VueJS app built as a side-project by me, Josué Orcière, in order to learn VueJS and understand its fundamentals. <br>
      The base version was built in under two weeks when I had some available time.
    </p>
    <p class="pt-10 max-w-3xl xl:text-lg">
      The app features daily puzzles, which are generated by Joackim Orcière who built a Python Sudoku generator, able to create problems with varying grid sizes (4x4, 9x9, 16x16...)
    </p>
    <p class="pt-10 max-w-3xl xl:text-lg">
      The app's main goal was to add some User Interactivity to replace the CLI initially used to play the game and solve the puzzles.
    </p>
    <p class="pt-10 max-w-3xl xl:text-lg">
      Currently, the app isn't complete, but it will automatically fetch new problems from the database and update them in order to find a new problem every day.<br>
      The problems are playable and every move will trigger a verification which will show the user wether it's a possible solution or not.<br>
      When a puzzle is solved, the grid turns green and you can't change the values any longer. <br><br>
      The goal would be to add more animations and user interactions to create an overall excellent experience.
    </p>
    

    <a
      href="https://github.com/jozrcr/kudosu"
      class="w-10 h-10 hover:opacity-80 duration-200 transition-all ease-in-out self-center mt-10"
      aria-label="Kudosu GitHub"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        class="fill-white"
      ><path d="M12.001 2C6.47598 2 2.00098 6.475 2.00098 12C2.00098 16.425 4.86348 20.1625 8.83848 21.4875C9.33848 21.575 9.52598 21.275 9.52598 21.0125C9.52598 20.775 9.51348 19.9875 9.51348 19.15C7.00098 19.6125 6.35098 18.5375 6.15098 17.975C6.03848 17.6875 5.55098 16.8 5.12598 16.5625C4.77598 16.375 4.27598 15.9125 5.11348 15.9C5.90098 15.8875 6.46348 16.625 6.65098 16.925C7.55098 18.4375 8.98848 18.0125 9.56348 17.75C9.65098 17.1 9.91348 16.6625 10.201 16.4125C7.97598 16.1625 5.65098 15.3 5.65098 11.475C5.65098 10.3875 6.03848 9.4875 6.67598 8.7875C6.57598 8.5375 6.22598 7.5125 6.77598 6.1375C6.77598 6.1375 7.61348 5.875 9.52598 7.1625C10.326 6.9375 11.176 6.825 12.026 6.825C12.876 6.825 13.726 6.9375 14.526 7.1625C16.4385 5.8625 17.276 6.1375 17.276 6.1375C17.826 7.5125 17.476 8.5375 17.376 8.7875C18.0135 9.4875 18.401 10.375 18.401 11.475C18.401 15.3125 16.0635 16.1625 13.8385 16.4125C14.201 16.725 14.5135 17.325 14.5135 18.2625C14.5135 19.6 14.501 20.675 14.501 21.0125C14.501 21.275 14.6885 21.5875 15.1885 21.4875C19.259 20.1133 21.9999 16.2963 22.001 12C22.001 6.475 17.526 2 12.001 2Z" /></svg>
    </a>

  </div>
</template>